### PR TITLE
fix version output

### PR DESCRIPTION
**Pull request by individual-it**
adjust the output of the version command to the reality

### CODE REVIEW

**Comment by individual-it** [comment]
we would have to update it every day ;-) https://github.com/owncloud/ocis/issues/6124

**Comment by mmattel** [comment]
> we would have to update it every day ;-) [owncloud/ocis#6124](https://github.com/owncloud/ocis/issues/6124)

Not correct, because `{ocis-stable}` resolves to 2.0.0
Both attributes will get updated only when a new stable release gets published.
It has nothing to do with daily builds.

**Comment by mmattel** [comment]
Note that the attributes (variables) here in the ocis repo are "local" and will only have relevance when doing a local build. For the web, the attribute is defined equally in the docs repo as this repo will include all repos and makes the final complete build. I have updated the docs repo just now so we can merge this easily and building wil be fine.

**Comment by mmattel** [comment]
Here is a screenshot of the rendered version:
image

**Pull request merged**
